<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>DhirDharLicenseGenerator</AssemblyName>
    <RootNamespace>DhirDhar.LicenseGenerator</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64;AnyCPU</Platforms>

    <!-- Application Icon & Output Settings -->
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
    <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>

    <!-- Self-contained Single-file Publishing Settings -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <DebugType Condition="'$(Configuration)' == 'Release'">none</DebugType>
    <DebugSymbols Condition="'$(Configuration)' == 'Release'">false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\AppIcon.ico" />
    <EmbeddedResource Include="Assets\DhirDharLogo.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DhirDhar.Application\DhirDhar.Application.csproj" />
    <ProjectReference Include="..\DhirDhar.Infrastructure\DhirDhar.Infrastructure.csproj" />
  </ItemGroup>

</Project>
