<Project>
  <PropertyGroup>
    <Platform Condition="'$(Platform)' == ''">x64</Platform>
    <Version>2.1.1</Version>
    <AssemblyVersion>2.1.1.0</AssemblyVersion>
    <FileVersion>2.1.1.0</FileVersion>
    <InformationalVersion>2.1.1</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
</Project>
